### ISSUE TITLE
Irregularity with Lucide icons

### ISSUE THREAD

**Issue by cuebit** [antfu/icones#101]
### Describe the bug

Thanks for adding the Lucide icon set 👍 

There seem to be irregularities with what is shown in the Icon Explorer vs what is visible via Iconify and UnoCSS playgrounds.

For example, the `sort-asc` and `sort-desc` icons are a different variant from what Iconify and UnoCSS portray.

Icones: [`sort-asc`/`sort-desc`](https://icones.js.org/collection/lucide?s=sort-)
Iconify: [`sort-asc`/`sort-desc`](https://icon-sets.iconify.design/lucide/?query=sort)
UnoCSS: [`sort-asc`](https://uno.antfu.me/?s=i-lucide-sort-asc)/[`sort-desc`](https://uno.antfu.me/?s=i-lucide-sort-desc)

### Reproduction

https://icones.js.org/collection/lucide?s=sort-

### System Info

```Shell
System:
  OS: macOS 12.6
  CPU: (10) arm64 Apple M1 Max
  Memory: 152.05 MB / 32.00 GB
  Shell: 5.8.1 - /bin/zsh
Binaries:
  Node: 16.14.2 - ~/.nvm/versions/node/v16.14.2/bin/node
  Yarn: 1.22.19 - ~/.nvm/versions/node/v16.14.2/bin/yarn
  npm: 8.19.2 - ~/.nvm/versions/node/v16.14.2/bin/npm
Browsers:
  Chrome: 106.0.5249.119
  Firefox: 106.0.1
  Safari: 16.0
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyberalien** [comment]
Looks the same to me. What differences do you see?
