### ISSUE TITLE
Broken fluent emoji

### ISSUE THREAD

**Issue by Zombobot1** [antfu/icones#102]
### Describe the bug

Emoji contains broken lips

![image](https://user-images.githubusercontent.com/48030070/198387074-4c2236d3-d338-4d74-b51d-5f4f0df99365.png)

Original
![image](https://user-images.githubusercontent.com/48030070/198387112-cfe8d6d6-3f9b-4db3-bc96-a84c1751afab.png)

### Reproduction

Search fluent-emoji:woman-office-worker-medium-light on icones.js.org

### System Info

```Shell
-
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyberalien** [comment]
Thanks for reporting! That's a bug in Microsoft repository: https://raw.githubusercontent.com/microsoft/fluentui-emoji/main/assets/Woman%20office%20worker/Medium-Light/Color/woman_office_worker_color_medium-light.svg

Repository: https://github.com/microsoft/fluentui-emoji

Emoji is correct in source Figma file, so something went wrong during export. Want to make a ticket there or shall I?

**Comment by cyberalien** [comment]
Reported bug to Microsoft: https://github.com/microsoft/fluentui-emoji/issues/77

**Comment by cyberalien** [comment]
Closing this because bug is upstream, it has been reported there and there is nothing to do now.

Update is automatic, so as soon as Microsoft developers fix that icon, it will be fixed in Iconify and Icones.
