### ISSUE TITLE
Case-insensitive search

### ISSUE THREAD

**Issue by adiba** [antfu/icones#104]
### Clear and concise description of the problem

Currently, searching for "Apple" shows no results, whereas searching for "apple" shows 177 results.

### Suggested solution

Case-insensitive search.
Options:
1. If all icon names are lowercase, we can use `String.prototype.toLower` on the search term without any issues.
2. Regex case insensitive match.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by Explosion-Scratch** [comment]
Seems like this implemented now:
<img width="1019" alt="image" src="https://github.com/antfu/icones/assets/61319150/0b3d5d32-1187-42d0-a698-4ea77e144256">
<img width="1026" alt="image" src="https://github.com/antfu/icones/assets/61319150/5db16993-e88e-4e34-ab7e-115b2ff4cf03">
