### ISSUE TITLE
Add common aliases

### ISSUE THREAD

**Issue by Idered** [antfu/icones#105]
### Clear and concise description of the problem

I searched https://icones.js.org/collection/ph for `cog`, `settings` but I could not find what I was looking for. I went to original icon package page and searched for `cog` - I got `gear` icon in results. 

### Suggested solution

Add common aliases e.g `['cog', 'gear', 'settings']` if you type any of those, it should also show icons matching other strings

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
That's an awesome idea! I been thinking to have such for a long while. But I am not sure if it's easy to do. We might want to load an English dictionary to do that? If you are interested in that, PR welcome!

**Comment by Idered** [comment]
I'll give it a try
