### ISSUE TITLE
Suggestion: set `/collections/all` as the homepage

### ISSUE THREAD

**Issue by innocenzi** [antfu/icones#116]
### Clear and concise description of the problem

I'm using icones.js.org almost every day to build my apps, and I don't think the index page has been useful even once. 

I always want to be able to search for icons by name right away, narrowing down by collections occasionally thanks to the sidebar at the left.

### Suggested solution

I would like to suggest to remove the index page to always land on `/collections/all`, as this page contains everything we need: favorited categories, category list and search, and most importantly the list of icons and its search input.

I would love to PR that if you give me your go.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by innocenzi** [comment]
I could, but I usually just type `icones.js.org` in my address bar instead of looking for a bookmark (which I had but never got to get used to lol)

The point of the issue though is that the homepage doesn't really bring value in my opinion, because `/collections/all` has all we could look for and even more

**Comment by antfu** [comment]
This is subjective. It doesn't bring you value doesn't mean it's not to the others. I won't take any action on this, you might figure out a workaround on your side, or fork it.

**Comment by innocenzi** [comment]
Sorry if I sounded rude, I specifically said "in my opinion". Thanks for considering anyway.

**Comment by innocenzi** [comment]
@antfu just wanna say thank you for the recent update that essentially fixes this issue by adding the ability to search icons from the home page ♥️
