### ISSUE TITLE
Add Font Awesome 6

### ISSUE THREAD

**Issue by petervangennip** [antfu/icones#117]
### Clear and concise description of the problem

Font Awesome 6 library missing

### Suggested solution

Add Font Awesome 6 library

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
It is already available:
- https://icones.js.org/collection/fa6-solid
- https://icones.js.org/collection/fa6-regular
- https://icones.js.org/collection/fa6-brands
