### ISSUE TITLE
Copy the icon

### ISSUE THREAD

**Issue by i1Zeus** [antfu/icones#118]
### Describe the bug

I can't copy the icon as a svg or anything, the only thing I'm able to do is to brows icons.

### Reproduction

the ability to copy and paste

### System Info

```Shell
windows 11.
vs code
```

### Used Package Manager

npm

### Validations

- [x] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyberalien** [comment]
What browser are you using?

**Comment by i1Zeus** [comment]
> 

edge

**Comment by cyberalien** [comment]
Edge supports Clipboard API. Check your addons, probably something is interfering with clipboard.

**Comment by sjqw** [comment]
在vue3中发现,循环渲染的时候,通过类名加载的图标无效

**Comment by i1Zeus** [comment]
@cyberalien 
mate I am using the extension in vs code that allow me to view and copy icons form the code editor it's self.

**Comment by cyberalien** [comment]
Tested extension and it indeed doesn't work. Probably extension needs to do some extra work to get access to clipboard.

**Comment by Ayyoub-ESSADEQ** [comment]
> ### Describe the bug
> I can't copy the icon as a svg or anything, the only thing I'm able to do is to brows icons.
> 
> ### Reproduction
> the ability to copy and paste
> 
> ### System Info
> ```shell
> windows 11.
> vs code
> ```
> 
> ### Used Package Manager
> npm
> 
> ### Validations
> * [x]  Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
> * [x]  Read the [Contributing Guide](https://github.com/antfu/contribute).
> * [x]  Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
> * [x]  Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
> * [x]  The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

The same issue I encounter while developing a figma plugin. I think the problem is with the navigator.clipboard API that doesn't work over an insecure connection like http protocol (which is inconvenient in the development phase). I suggest to move from relying on the browser clipboard to an alternative library like a Clipboard.js
