### ISSUE TITLE
Output valid React JSX

### ISSUE THREAD

**Issue by egoist** [antfu/icones#12]
It should convert kebab-case like `stroke-width` to camelCase 🤔

**Comment by antfu** [comment]
Which icon set you are using when facing this issue? I didn't found an icon with this attr.

**Comment by egoist** [comment]
for example this is the JSX output of `heroicons-outline:search` from heroicons:

```jsx
<svg focusable="false" width="1em" height="1em" viewBox="0 0 24 24">
<g fill="none">
<path 
d="M21 21l-6-6m2-5a7 7 0 1 1-14 0a7 7 0 0 1 14 0z" 
stroke="currentColor" 
stroke-width="2" 
stroke-linecap="round" 
stroke-linejoin="round"></path>
</g>
</svg>
```

**Comment by antfu** [comment]
Fixed. Thanks
