### ISSUE TITLE
Add new icons to collection

### ISSUE THREAD

**Issue by Tarcio-Rick** [antfu/icones#123]
### Clear and concise description of the problem

Please, add iconsax.io to collection. 
The icons are very beautiful

### Suggested solution

Mentioned above

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
It is not open source.
