### ISSUE TITLE
Use tauri.rs (instead of electron) to build desktop apps.

### ISSUE THREAD

**Issue by ArishSultan** [antfu/icones#14]
You are planning to create electron client, instead of using electron, i would recommend you to use tauri.rs to build cross platform desktop application.

Main benefit of using tauri.rs is that it is built using rust so, performance is no issue, moreover the build (release) size of an electron app is too big.

Minimum size of electron varies from 50mb to 70mb as far as i have seem

But tauri gives u minimum size oh 600kb

I would also like to contribute if u use tauri 😁

**Comment by antfu** [comment]
Sounds great. I also found the electron is too complex to setup the build. I have no experience with `tauri.rs` but it looks promising and I would love it give a try.

Is there any limitation for `tauri.rs` though? Actually, all I need is only a static server to serve the dist files.

It would be great if you would like to help with it. Thanks!

**Comment by antfu** [comment]
I don't think we need too much setup either. Let's go with it! Would you like to make draft PR so we can work on it? Thanks a lot!

**Comment by ArishSultan** [comment]
Yes Why not, i will create a PR

**Comment by mrleblanc101** [comment]
I'm confused, is there a desktop app ?
The readme still says "Electron coming"
