### ISSUE TITLE
Link to specific icons

### ISSUE THREAD

**Issue by robokozo** [antfu/icones#142]
### Clear and concise description of the problem

I often want to verify a particular icon with designers/management. Right now, the easiest way is to search for a potential icon and take a screenshot. I want an easier way of sharing links to specific icons.

### Suggested solution

When selecting an icon, a 'drawer' opens up from the bottom of the screen. My suggestion is to 'drive' the drawer with a URL query parameter

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by LanFeusT23** [comment]
Same concern here! A direct link would be awesome.

**Comment by antfu** [comment]
PR welcome :)
