### ISSUE TITLE
Svelte output should be plain HTML, not JSX

### ISSUE THREAD

**Issue by dylanbr0wn** [antfu/icones#143]
### Describe the bug

Svelte 3 templating syntax is [plain HTML](https://svelte.dev/docs#template-syntax-tags), whereas the Svelte icon output is JSX.

Willing to submit a PR to just clean SVG and skip JSX conversion.

### Reproduction

https://svelte.dev/repl/dc2dcdfc6c2040ffa3bef8da3bd13ae2?version=3.58.0

### System Info

```Shell
System:
    OS: macOS 13.4
    CPU: (8) arm64 Apple M1
    Memory: 98.72 MB / 16.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 18.12.0 - ~/.volta/tools/image/node/18.12.0/bin/node
    Yarn: 1.22.19 - ~/.volta/tools/image/yarn/1.22.19/bin/yarn
    npm: 8.19.2 - ~/.volta/tools/image/node/18.12.0/bin/npm
  Browsers:
    Firefox: 109.0.1
    Safari: 16.5
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by 5ubh4d45** [comment]
This issue is still not resolved. I have a solution ready with correct svelte output which inherits props to change attributes dynamically. Should I create a PR if no one is working on it?
