### ISSUE TITLE
Favorite button in recent collection card

### ISSUE THREAD

**Issue by arashsheyda** [antfu/icones#148]
### Clear and concise description of the problem

The recent collections doesn't have a favorite button, do ou think is it a good idea to have?

### Suggested solution

Something like this:
![image](https://github.com/antfu/icones/assets/38922203/4447a08f-3b51-4733-b8d2-5da4cd3947ca)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Sounds good, PR welcome :)
