### ISSUE TITLE
Bag: Download zip not working

### ISSUE THREAD

**Issue by AustinGil** [antfu/icones#160]
### Describe the bug

When I try to download the Zip file from the bag, it does not work. There is just an error in the console.

### Reproduction

Open app > Add icon to bag > Open Bag > Click Download Zip > select any of the download options

### System Info

```Shell
https://icones.js.org/ in Edge and Chrome
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Seems to work for me. What's the error you are seeing?

**Comment by AustinGil** [comment]
Unfortunately, it's not a very helpful error. It's just the name of the first icon in the bag.

[Screen Recording - Made with RecordCast.webm](https://github.com/antfu/icones/assets/4879075/a7b71615-24fb-43a2-aa64-203760c55152)

**Comment by SharerMax** [comment]
When collection name contain `-`, full icon name will be converted only has `-`. So API of *iconify* can't parse collection name correctly.

https://github.com/antfu/icones/blob/348eab1d9d864afcf915e71f0874217e805c2425/src/components/Bag.vue#L28-L34

e.g.
  `material-symbols:15mp-outline-rounded` -> `material-symbols-15mp-outline-rounded`
  collection name: material
  icon name: symbols-15mp-outline-rounded
   https://api.iconify.design/material.json?icons=symbols-15mp-outline-rounded  ( from `loadIcon`)404
   https://api.iconify.design/material-symbols-15mp-outline-rounded.svg 404 (from api)

 But, we can use origin name to keep `:` as separator between collection and icon. *Iconify*
 can parse collection name and icon name correctly.
  collection name: material-symbols
  icon name: 15mp-outline-rounded
  https://api.iconify.design/material-symbols.json?icons=15mp-outline-rounded  200 OK
  https://api.iconify.design/material-symbols:15mp-outline-rounded.svg 200 OK
