### ISSUE TITLE
Download zip functionality broken on website

### ISSUE THREAD

**Issue by afzalsayed96** [antfu/icones#24]
![Screen Shot 2020-10-11 at 1 22 48 PM](https://user-images.githubusercontent.com/14029371/95673308-fa8d6c80-0bc4-11eb-804c-354e333db6fb.png)

![Screen Shot 2020-10-11 at 1 23 55 PM](https://user-images.githubusercontent.com/14029371/95673321-0b3de280-0bc5-11eb-8cf1-9d8aebed06d6.png)

**Comment by afzalsayed96** [comment]
Bug seems to be introduced in this [commit](https://github.com/antfu/icones/commit/943f03b4e0e01c14b226d0a839efb5b7e6fc2a3c)

**Comment by antfu** [comment]
Should be fixed. Thanks!
