### ISSUE TITLE
Version select

### ISSUE THREAD

**Issue by Avaray** [antfu/icones#252]
### Clear and concise description of the problem

Would be nice to have possibility to choose version of iconify, to see list of icons available only in that specific version.

I started using [Astro](https://astro.build/) with the only reasonable at this moment library [astro-icon](https://github.com/natemoo-re/astro-icon). Unfortunately astro-icon uses `iconify/json` in version `1.1.461` that was released 2 years ago. Most of my favourite icons are not there. I wish to know which icons are available, but I have no idea how to browse icons from that old versions. So, that's how **this idea** came about.

### Suggested solution

Possibility to browse icons from old versions.

### Alternative

Upload file of old version to be able to browse them?

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
Can't you just install latest `@iconify/json` as dependency?

**Comment by Avaray** [comment]
> Can't you just install latest `@iconify/json` as dependency?
> 
> edit: if npm complains about version mismatch, try `pnpm` instead. It can be configured to override dependency of any package.

Thanks for advice. I'm pretty sure I did it with pnpm at the very beginning and it didn't work. But I will try again tomorrow.

**Comment by antfu** [comment]
I am not sure if this is something that worth the effort to support something legacy. I think it would be more reasonable to wait for astro-icons to keep up-to-date. Otherwise you might fork this project and upgrade the icondata on your local to see.

**Comment by Avaray** [comment]
I agree. Backward compatibility can be problematic.
