### ISSUE TITLE
Website seems to be down

### ISSUE THREAD

**Issue by Robbie-Cook** [antfu/icones#27]
Hey @antfu , I love this website!

Both https://icones.netlify.app and https://icones.js.org seem to be down, they are showing a blank screen. No errors in the console though, and the network requests seem to be ok.

Thanks!

**Comment by antfu** [comment]
Oops, thanks for the notice! I have reverted the commit and it should be fine now. I will see if I can fix it with vite later.

**Comment by Robbie-Cook** [comment]
@antfu Thanks! Appreciate it!
