### ISSUE TITLE
The search query is not synchronized with the input value

### ISSUE THREAD

**Issue by cyanxxx** [antfu/icones#296]
### Describe the bug

When I delete the search value to empty, the search query still retains a value.
![Icônes](https://github.com/antfu/icones/assets/23733571/29e89518-a4dd-4c0d-875f-40884dc6a12f)

### Reproduction

Input some value in the search input and delete the text to empty

### System Info

```Shell
Edge: Chromium (122.0.2365.92)
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyanxxx** [comment]
May I submit a pr to fix this?

**Comment by antfu** [comment]
Sure, PR welcome!
