### ISSUE TITLE
Global icon search option

### ISSUE THREAD

**Issue by manojVivek** [antfu/icones#3]
Hey @antfu, thank you so much for this project. This is so useful. 🚀 

This is a suggestion to add a global search option that will show results across all icon packs for the given query. This will be handy to select an icon comparing across all the packs.

Thanks again.

**Comment by antfu** [comment]
Thanks, glad it to be helpful :). Did you try https://icones.netlify.app/collection/all?

**Comment by antfu** [comment]
Oh I see, you are using mobile right? There is currently no entry for that but you can still use the url. Will try to figure out a good spot for it.

**Comment by manojVivek** [comment]
Yeah, that is exactly what I was looking for. Just didn't notice the `All` option at the top. 

Thanks for the help. 👍
