### ISSUE TITLE
<symbol>

### ISSUE THREAD

**Issue by silvenon** [antfu/icones#30]
Beautiful app 😍 Are there any plans for SVG sprites with `<symbol>` tags, like [IcoMoon](https://icomoon.io/) has?

**Comment by antfu** [comment]
Oh, I didn't know that. Would you mind to send a PR? Thanks

**Comment by silvenon** [comment]
Maybe. My proposition would be to change the label of the "SVG" button in Snippets to "`<svg>`", then add another button labelled "`<symbol>`".
