### ISSUE TITLE
Unable to navigate to the other collection page after search

### ISSUE THREAD

**Issue by cyanxxx** [antfu/icones#300]
### Describe the bug

When I click the collection link in the detail icon panel, the navigation fails.
![Icônes](https://github.com/antfu/icones/assets/23733571/209ab546-23f5-4f09-8dea-1ce00e2863c7)

I think this issue occurs because when you click to navigate, it triggers the set handler of current. The set handler gets the old route and navigate the wrong url.
![image](https://github.com/antfu/icones/assets/23733571/facd2e88-0694-46e3-89d4-0674cfabda07)

### Reproduction

Searching first and click the collenction in the detail icon panel

### System Info

```Shell
Edge: Chromium (122.0.2365.92)
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by antfu** [comment]
Yeah, I noticed that too. Do you want to send a PR to fix it? Thanks
