### ISSUE TITLE
Large icons are smaller

### ISSUE THREAD

**Issue by sibbng** [antfu/icones#32]
Large icons are has become smaller than small icons.

**Comment by antfu** [comment]
Can you provide more context? Thanks

**Comment by sibbng** [comment]
Changing icon size to Large on actions menu results with a smaller icons when compared to Small option.

![image](https://user-images.githubusercontent.com/19991745/108799274-c481d100-7544-11eb-8c98-6ea712837252.png)

**Comment by antfu** [comment]
Thanks! Fixed
