### ISSUE TITLE
Support OpenSearch

### ISSUE THREAD

**Issue by peteruithoven** [antfu/icones#33]
> The [OpenSearch description format](http://www.opensearch.org/Specifications/OpenSearch/1.1#OpenSearch_description_document) lets a website describe a search engine for itself, so that a browser or other client application can use that search engine. OpenSearch is supported by (at least) Firefox, Edge, Internet Explorer, Safari, and Chrome. 

More info: https://developer.mozilla.org/en-US/docs/Web/OpenSearch

Screenshots of using this in Firefox:
![screenshot from 2019-01-29 18 01 04 2x](https://user-images.githubusercontent.com/523210/51926327-587a2080-23f1-11e9-9e52-d493bc6fe4fc.png)
![screenshot from 2019-01-29 18 00 35 2x](https://user-images.githubusercontent.com/523210/51926330-587a2080-23f1-11e9-9159-c997605e0641.png)

**Comment by Explosion-Scratch** [comment]
Seems like this is already implemented:
https://github.com/antfu/icones/commit/952751213b45b246c2157c35cbdb56ae4df75fcc
