### ISSUE TITLE
Copying icons as px

### ISSUE THREAD

**Issue by sibbng** [antfu/icones#35]
When copying an icon its width and height are like that:  

```html
width="1em" height="1em"
```

An option to copy it like that would be awesome.

```html
width="16" height="16"
````

Motivation: When pasting that icon into Figma, it thinks its width and height as 1.

**Comment by antfu** [comment]
Yeah, I notice this too. Would you like to create a PR? I think it makes sense to copy/download SVG as `64` and components leaving as `1em`
