### ISSUE TITLE
Unclear which prefix to use whilst browsing a specific library

### ISSUE THREAD

**Issue by Blastius** [antfu/icones#37]
First of all, really awesome repo :)

When I'm looking through a library, for example Font Awesome 5 Solid, I can't see which prefix to use with these icons:
![afbeelding](https://user-images.githubusercontent.com/10246822/127128229-cdc746ae-3dc8-4a90-8a45-4c5758666708.png)

So when I want to use `abacus`, I need to search through the All category, which gives me the following tooltip, including the shown prefix:
![afbeelding](https://user-images.githubusercontent.com/10246822/127128257-07126325-c9ac-4d0f-b940-a32fd21c4ea9.png)

It would be really nice to see the library prefix on the library page itself, or atleast within the tooltip like it is showing when searching through All.

**Comment by Blastius** [comment]
As I was creating this issue and looking at my screenshots, it became clear to me that the prefix of a library is shown within the end of the URL.. 

Up to you for closing this issue or make it an enhancement.

**Comment by antfu** [comment]
The hover it shorten by design, and you can always click the button to see the full icon id in the detailed page.

**Comment by Blastius** [comment]
I wasn't aware of the click info, my bad. Thanks!
