### ISSUE TITLE
Wrong (unrelated) search result

### ISSUE THREAD

**Issue by ngekoding** [antfu/icones#41]
Just trying to find an icon in Material Design Icons with a keyword `user`, but it showing unrelated results.

And I try to compare it with MDI Explorer and from the site https://materialdesignicons.com which get a better results.

Here is the screenshots.

<img width="1280" alt="Result on vscode icones & mdi explorer" src="https://user-images.githubusercontent.com/11625690/137516236-c29d07d1-bb79-4d00-9dce-a5a88c152f57.png">

<img width="1280" alt="Result on material design icons website" src="https://user-images.githubusercontent.com/11625690/137516249-d6fae220-3e7e-4386-8f0e-fb9fccdf4104.png">

**Comment by antfu** [comment]
![image](https://user-images.githubusercontent.com/11247099/137529966-b7370172-3f2f-4499-bc98-e2df8fa41187.png)
