### ISSUE TITLE
Add iconsax

### ISSUE THREAD

**Issue by X7md** [antfu/icones#43]
## Request add new icon package.
 
iconsax the official icons of the [Vuesax](https://vuesax.com/) framework.

[Iconsax WebSite](https://github.com/lusaxweb/iconsax)

[GitHub Repo](https://github.com/lusaxweb/iconsax)

### License
https://iconsax.io/#license

![image](https://user-images.githubusercontent.com/54203033/141686650-e6c8834b-c1bb-4172-baef-0810512776d0.png)

**Comment by antfu** [comment]
Please request at https://github.com/iconify/iconify
