### ISSUE TITLE
Hidden icon sets

### ISSUE THREAD

**Issue by cyberalien** [antfu/icones#44]
It appears Mono Icons were added twice: in mi.json and mono-icons.json: https://github.com/iconify/collections-json/issues/21

To fix that issue, I've added `hidden` boolean property to `IconifyInfo` type (types and info conversion function in utils have been updated as well) and latest version of `@iconify/json` package contains `hidden` property for mono-icons:

```json
	"mono-icons": {
		"name": "Mono Icons",
		"total": 180,
		"author": "Mono",
		"url": "https://github.com/mono-company/mono-icons",
		"license": "MIT",
		"licenseURL": "https://github.com/mono-company/mono-icons/blob/master/LICENSE.md",
		"height": 24,
		"samples": [
			"user",
			"log-in",
			"play"
		],
		"version": "1.3.1",
		"palette": "Colorless",
		"category": "General",
		"hidden": true
	},
```

So icon set is still there to avoid breaking people's UI, but it is hidden so it no longer should appear in icon sets list.

**Comment by antfu** [comment]
Implemented.
