### ISSUE TITLE
CSS file Missing

### ISSUE THREAD

**Issue by Soya-xy** [antfu/icones#62]
`https://d33wubrfki0l68.cloudfront.net/css/df63ff0ba9fa2d267f10200f991187c694b39ef5/assets/index.178bdaef.css`
Visit `https://icones.js.org/` and find that the CSS file resource is missing and cannot be accessed

**Comment by antfu** [comment]
I don't think this is related to this project. 🤔

**Comment by Soya-xy** [comment]
> I don't think this is related to this project. 🤔
Sorry, it's my network problem
