### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by Explosion-Scratch** [antfu/icones#65]
![image](https://user-images.githubusercontent.com/61319150/162293214-3a46f4ca-57a6-47bd-86a1-c6a29ffbf70a.png)
![image](https://user-images.githubusercontent.com/61319150/162293962-5abcb577-72f6-41c6-bd0d-701511ec7dca.png)

**Comment by antfu** [comment]
I have no problem accessing it. Probably some glitch on Cloudflare or Netlify side

**Comment by Explosion-Scratch** [comment]
Sorry, no longer down
