### ISSUE TITLE
Add govicons.io

### ISSUE THREAD

**Issue by mika76** [antfu/icones#87]
### Clear and concise description of the problem

http://govicons.io/ a whole bunch of font-awesome type icons for government use...

### Suggested solution

http://govicons.io/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
Please request to Iconify instead. Thanks.
