### ISSUE TITLE
Order Icon Packs alphabetically or add option to do so

### ISSUE THREAD

**Issue by BaumianerNiklas** [antfu/icones#88]
### Clear and concise description of the problem

Right now we obviously have a way to search through all icons which works great. Sometimes though you might also want to look for icon packs, for example if you limit your design system to only a few packs, want to quickly lookup the prefix of a pack, or have a general idea of how the pack is called but don't know its exact name, etc. Currently though the Icon packs seem to be sorted in a completely arbitrary order, so finding a specific one gets annoying. 

### Suggested solution

Sort the icon packs in both the home view and the sidebar in alphabetical order. Could also go further and add a setting for a "sort mode" where you could set the way icon packs should be ordered (e.g. by name, size, etc.), similar to how there is a "Size" display option for icons.

### Alternative

You could use the browser built-in search (`CTRL-F`) but that gets finnicky, plus it wouldn't really help if you don't know a packs' exact name.

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by antfu** [comment]
PR welcome!
