### ISSUE TITLE
Add Heroicons v2.0

### ISSUE THREAD

**Issue by marcfilleul** [antfu/icones#91]
### Clear and concise description of the problem

Hi,

Tailwind Labs just released [Heroicons v2.0](https://heroicons.com/), which is a brand new icon set which includes 280 icons drawn in three distinct styles:

- Outline — line icons with a 1.5px stroke, drawn in a 24px view box.
- Solid — solid icons with filled shapes, drawn in a 24px view box.
- Mini — solid icons with filled shapes, drawn in a 20px view box.

Would it be possible to add this new set?

Thanks.
Best regards.

### Suggested solution

Add [Heroicons v2.0](https://heroicons.com/)

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by FallDownTheSystem** [comment]
The new HeroIcons set has already been added to iconify's icon sets, so I believe all that's left to do is to update iconify.

Although, I'm wondering if this repo could/should pull the latest sets automatically, or in a scheduled trigger?
