### ISSUE TITLE
Add Feather Icons

### ISSUE THREAD

**Issue by brc-dd** [antfu/icones#93]
The ones currently present on the app (https://icones.js.org/collection/fe) are "Feather Icon" which are different from "Feather Icons" (https://icon-sets.iconify.design/feather/).

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
It is available as Lucide: https://icones.js.org/collection/lucide

Feather Icons project has been dead for long time, Lucide is a fork that is actively maintained. It contains all icons from Feather Icons + some new icons and fixes. See https://github.com/lucide-icons/lucide

**Comment by brc-dd** [comment]
Ah, thanks for letting me know 🙌
