### ISSUE TITLE
Copy to clipboard doesn't work in Safari

### ISSUE THREAD

**Issue by kimblim** [antfu/icones#98]
### Describe the bug

When selecting an icon and trying to copy the code to the local clipboard only empty lines are actually copied. I've tried copying SVG, React, React with TS, Vue but none of them worked.

This happens in Safari 16 on MacOS Monterey 12.6.

### Reproduction

Open https://icones.js.org/collection/flagpack, choose a random flag, click on one of the copy buttons and then paste into a text editor.

### System Info

```Shell
System:
    OS: macOS 12.6
    CPU: (10) arm64 Apple M1 Pro
    Memory: 83.20 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 18.5.0 - ~/Library/Caches/fnm_multishells/52382_1666189874732/bin/node
    Yarn: 1.22.19 - ~/Library/Caches/fnm_multishells/52382_1666189874732/bin/yarn
    npm: 8.12.1 - ~/Library/Caches/fnm_multishells/52382_1666189874732/bin/npm
  Browsers:
    Chrome: 106.0.5249.119
    Firefox: 105.0.2
    Safari: 16.0
```

### Used Package Manager

n/a

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by cyberalien** [comment]
Should be fixed now... accidentally merged PR for fixing this without review process when fixing icon sets, but clipboard fix does work.
