### ISSUE TITLE
Add lucide icons

### ISSUE THREAD

**Issue by VladimirCores** [antfu/icones#99]
### Clear and concise description of the problem

Feature request to add set of icons from https://lucide.dev/

### Suggested solution

lucide icons are searchable from https://icones.js.org/

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that request the same feature to avoid creating a duplicate.

**Comment by cyberalien** [comment]
It is already available: https://icones.js.org/collection/lucide
